---
- name: get system info
  setup: gather_subset=network filter=ansible_*
  register: sysinfo
- name: approve operation
  when: sysinfo|success
  shell: echo "everything is gonna be alright!" | tee -i /home/vnaumov/OK.txt
  register: ok

- debug:
    msg: "{{ ok.stdout }}"

- debug:
    msg: " here is network configuration{{ sysinfo }}"
